language: node_js
node_js:
  - "8.1.3"

cache:
  directories:
    - node_modules

before_script:
  - sudo -- sh -c -e "echo '127.0.0.1	localhost.firebaseio.test' >> /etc/hosts"

script:
  - npm test
  - npm run lint

notifications:
  slack: link-up-group:CDs71nA1i9gYXueHfHghIjNe
