language: node_js
node_js:
  - "8.1.3"

cache:
  directories:
    - node_modules

addons:
  hosts:
    - localhost.firebaseio.test

script:
  - npm test
  - npm run lint

notifications:
  slack: link-up-group:CDs71nA1i9gYXueHfHghIjNe
